/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.system.ui;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.system.ui.internal.SystemActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SystemExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SystemActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SystemActivator.getInstance().getInjector(SystemActivator.EDU_KIT_IPD_SDQ_MDSDPC_SYSTEM_SYSTEM);
	}
	
}
