/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AllocationStandaloneSetup extends AllocationStandaloneSetupGenerated {

	def static void doSetup() {
		new AllocationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
