/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class AllocationRuntimeModule extends AbstractAllocationRuntimeModule {
}
