/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.system.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.mdsdpc.system.parser.antlr.internal.InternalSystemParser;
import edu.kit.ipd.sdq.mdsdpc.system.services.SystemGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SystemParser extends AbstractAntlrParser {

	@Inject
	private SystemGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSystemParser createParser(XtextTokenStream stream) {
		return new InternalSystemParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ComponentBasedSystem";
	}

	public SystemGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SystemGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
