/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.mdsdpc.mydsl.ui;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.mydsl.ui.internal.MydslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MydslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MydslActivator.getInstance().getInjector(MydslActivator.EDU_KIT_IPD_SDQ_MDSDPC_MYDSL_MYDSL);
	}
	
}
