/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment.ui;

import edu.kit.ipd.sdq.mdsdpc.environment.ui.AbstractEnvironmentUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EnvironmentUiModule extends AbstractEnvironmentUiModule {
  public EnvironmentUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
