/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation.validation;

import edu.kit.ipd.sdq.mdsdpc.allocation.validation.AbstractAllocationValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class AllocationValidator extends AbstractAllocationValidator {
}
