/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation.ui;

import edu.kit.ipd.sdq.mdsdpc.allocation.ui.AbstractAllocationUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class AllocationUiModule extends AbstractAllocationUiModule {
  public AllocationUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
