/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository;

import edu.kit.ipd.sdq.mdsdpc.repository.RepositoryStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RepositoryStandaloneSetup extends RepositoryStandaloneSetupGenerated {
  public static void doSetup() {
    RepositoryStandaloneSetup _repositoryStandaloneSetup = new RepositoryStandaloneSetup();
    _repositoryStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
