/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.mdsdpc.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {

	def static void doSetup() {
		new MyDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
