/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation;

import edu.kit.ipd.sdq.mdsdpc.allocation.AbstractAllocationRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class AllocationRuntimeModule extends AbstractAllocationRuntimeModule {
}
