/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment.ui.contentassist;

import edu.kit.ipd.sdq.mdsdpc.environment.ui.contentassist.AbstractEnvironmentProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EnvironmentProposalProvider extends AbstractEnvironmentProposalProvider {
}
