/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.system.scoping;

import edu.kit.ipd.sdq.mdsdpc.system.scoping.AbstractSystemScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SystemScopeProvider extends AbstractSystemScopeProvider {
}
