<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="componentBasedSystem" nsURI="edu.kit.ipd.sdq.mdsdpc.componentBasedSystem"
    nsPrefix="componentBasedSystem">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentBasedSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
        upperBound="-1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" upperBound="-1"
        eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" upperBound="-1" eType="#//dataTypes/Type"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblyconnector" upperBound="-1"
        eType="#//roles/AssemblyConnector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocation" lowerBound="1"
        eType="#//Allocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" lowerBound="1"
        eType="#//Repository" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//Environment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviourdescription" upperBound="-1"
        eType="#//behaviourDescription/BehaviourDescription" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="service" lowerBound="1"
        upperBound="-1" eType="#//Service" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" upperBound="-1"
        eType="#//roles/RequiredRole" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" lowerBound="1"
        eType="#//roles/ProvidedRole" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="signature" upperBound="-1"
        eType="#//Signature" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeComponent" eSuperTypes="#//Component">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="SameInterfaceDelegated RoleCount"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Ensures that there are as many connectors as there are roles in the composite component"/>
      </eAnnotations>
      <details key="SameInterfaceDelegated" value="&#xA;&#x9;&#x9;self.delegationconnector->&#xA;&#x9;&#x9;forAll( d | d.role->includes(providedrole) or d.role->includesAll(requiredrole))"/>
      <details key="RoleCount" value="&#xA;&#x9;&#x9;self.delegationconnector->size() = self.requiredrole->size() + self.providedrole->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" lowerBound="2"
        upperBound="-1" eType="#//AssemblyContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegationconnector" lowerBound="1"
        upperBound="-1" eType="#//DelegationConnector" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="2"
        upperBound="-1" eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Signature">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returntype" lowerBound="1"
        eType="#//dataTypes/ReturnType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parametertype" lowerBound="1"
        eType="#//dataTypes/ParameterType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AssemblyContext">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllocationContext">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" lowerBound="1"
        eType="#//AssemblyContext"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DelegationConnector">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="DelegationConnectorRolesType DelegationConnectorRolesInterface"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constraint ensures that the interface of the roles are the same"/>
      </eAnnotations>
      <details key="DelegationConnectorRolesType" value="&#x9;&#x9; &#xA;&#x9;&#x9;self.role->first().oclType() = self.role->last().oclType()"/>
      <details key="DelegationConnectorRolesInterface" value="&#x9;&#x9; &#xA;&#x9;&#x9;self.role->first().interface = self.role->last().interface"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="2" upperBound="2"
        eType="#//roles/Role"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Environment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" upperBound="-1"
        eType="#//Container" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" upperBound="-1" eType="#//Link"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="interface" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Allocation">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="NestedComponentAllocation"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constraint prohibits allocation of an assemblyContext (specified in AllocationContext),&#xA;if it is allocated inside a CompositeComponent"/>
      </eAnnotations>
      <details key="NestedComponentAllocation" value=" &#xA;&#x9;&#x9;let composites : Collection(CompositeComponent) = &#xA;&#x9;&#x9;self.allocationcontext->select(a | a.assemblycontext.component.oclIsTypeOf(CompositeComponent)).assemblycontext.component.oclAsType(CompositeComponent)&#xA;&#x9;&#x9;in self.allocationcontext.assemblycontext->excludesAll(composites.assemblycontext)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocationcontext" lowerBound="1"
        upperBound="-1" eType="#//AllocationContext" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service">
    <eStructuralFeatures xsi:type="ecore:EReference" name="correspondingSignatures"
        lowerBound="1" upperBound="-1" eType="#//Signature"/>
  </eClassifiers>
  <eSubpackages name="dataTypes" nsURI="edu.kit.ipd.sdq.mdsdpc.componentBasedSystem/dataTypes"
      nsPrefix="dataTypes">
    <eClassifiers xsi:type="ecore:EClass" name="Simple" eSuperTypes="#//dataTypes/ParameterType #//dataTypes/ReturnType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//dataTypes/simpleTypes"
          defaultValueLiteral="int"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Complex" eSuperTypes="#//dataTypes/ReturnType #//dataTypes/ParameterType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="simple" lowerBound="2"
          upperBound="-1" eType="#//dataTypes/Simple" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterType" eSuperTypes="#//dataTypes/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Void" eSuperTypes="#//dataTypes/ReturnType"/>
    <eClassifiers xsi:type="ecore:EClass" name="ReturnType" eSuperTypes="#//dataTypes/Type"/>
    <eClassifiers xsi:type="ecore:EClass" name="Type">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="simpleTypes">
      <eLiterals name="int"/>
      <eLiterals name="boolean" value="1"/>
      <eLiterals name="char" value="2"/>
      <eLiterals name="date" value="3"/>
      <eLiterals name="double" value="4"/>
      <eLiterals name="float" value="5"/>
      <eLiterals name="list" value="6"/>
      <eLiterals name="long" value="7"/>
      <eLiterals name="map" value="8"/>
      <eLiterals name="string" value="9"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="behaviourDescription" nsURI="edu.kit.ipd.sdq.mdsdpc.componentBasedSystem/behaviourDescription"
      nsPrefix="behaviourDescription">
    <eClassifiers xsi:type="ecore:EClass" name="BehaviourDescription"/>
    <eClassifiers xsi:type="ecore:EClass" name="InternalAction" eSuperTypes="#//behaviourDescription/BehaviourDescription"/>
    <eClassifiers xsi:type="ecore:EClass" name="ExternalCall" eSuperTypes="#//behaviourDescription/BehaviourDescription"/>
    <eClassifiers xsi:type="ecore:EClass" name="Loop" eSuperTypes="#//behaviourDescription/BehaviourDescription"/>
    <eClassifiers xsi:type="ecore:EClass" name="Branch" eSuperTypes="#//behaviourDescription/BehaviourDescription"/>
  </eSubpackages>
  <eSubpackages name="roles" nsURI="edu.kit.ipd.sdq.mdsdpc.componentBasedSystem/roles"
      nsPrefix="roles">
    <eClassifiers xsi:type="ecore:EClass" name="Role">
      <eStructuralFeatures xsi:type="ecore:EReference" name="interface" lowerBound="1"
          eType="#//Interface"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RequiredRole" eSuperTypes="#//roles/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProvidedRole" eSuperTypes="#//roles/Role"/>
    <eClassifiers xsi:type="ecore:EClass" name="AssemblyConnector">
      <eStructuralFeatures xsi:type="ecore:EReference" name="providedrole" lowerBound="1"
          eType="#//roles/ProvidedRole"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="requiredrole" lowerBound="1"
          eType="#//roles/RequiredRole"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="assemblycontext" lowerBound="2"
          upperBound="2" eType="#//AssemblyContext"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
