/*
 * generated by Xtext 2.9.2
 */
package edu.kit.ipd.sdq.mdsdpc.mydsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("edu/kit/ipd/sdq/mdsdpc/mydsl/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
