/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment.ui.tests;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.environment.ui.internal.EnvironmentActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class EnvironmentUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EnvironmentActivator.getInstance().getInjector("edu.kit.ipd.sdq.mdsdpc.environment.Environment");
	}

}
