/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository.ui.contentassist;

import edu.kit.ipd.sdq.mdsdpc.repository.ui.contentassist.AbstractRepositoryProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class RepositoryProposalProvider extends AbstractRepositoryProposalProvider {
}
