/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment.ui;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.environment.ui.internal.EnvironmentActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EnvironmentExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EnvironmentActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EnvironmentActivator.getInstance().getInjector(EnvironmentActivator.EDU_KIT_IPD_SDQ_MDSDPC_ENVIRONMENT_ENVIRONMENT);
	}
	
}
