/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository.ui.tests;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.repository.ui.internal.RepositoryActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class RepositoryUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RepositoryActivator.getInstance().getInjector("edu.kit.ipd.sdq.mdsdpc.repository.Repository");
	}

}
