/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment;

import edu.kit.ipd.sdq.mdsdpc.environment.AbstractEnvironmentRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EnvironmentRuntimeModule extends AbstractEnvironmentRuntimeModule {
}
