/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment;

import edu.kit.ipd.sdq.mdsdpc.environment.EnvironmentStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EnvironmentStandaloneSetup extends EnvironmentStandaloneSetupGenerated {
  public static void doSetup() {
    EnvironmentStandaloneSetup _environmentStandaloneSetup = new EnvironmentStandaloneSetup();
    _environmentStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
