/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EnvironmentRuntimeModule extends AbstractEnvironmentRuntimeModule {
}
