/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.environment


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EnvironmentStandaloneSetup extends EnvironmentStandaloneSetupGenerated {

	def static void doSetup() {
		new EnvironmentStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
