/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository.ui;

import com.google.inject.Injector;
import edu.kit.ipd.sdq.mdsdpc.ComponentBasedSystem.repository.ui.internal.RepositoryActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RepositoryExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RepositoryActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RepositoryActivator.getInstance().getInjector(RepositoryActivator.EDU_KIT_IPD_SDQ_MDSDPC_REPOSITORY_REPOSITORY);
	}
	
}
