/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.mdsdpc.repository.parser.antlr.internal.InternalRepositoryParser;
import edu.kit.ipd.sdq.mdsdpc.repository.services.RepositoryGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class RepositoryParser extends AbstractAntlrParser {

	@Inject
	private RepositoryGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRepositoryParser createParser(XtextTokenStream stream) {
		return new InternalRepositoryParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Repository";
	}

	public RepositoryGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RepositoryGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
