/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.system;

import edu.kit.ipd.sdq.mdsdpc.system.AbstractSystemRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SystemRuntimeModule extends AbstractSystemRuntimeModule {
}
