/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.system;

import edu.kit.ipd.sdq.mdsdpc.system.SystemStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SystemStandaloneSetup extends SystemStandaloneSetupGenerated {
  public static void doSetup() {
    SystemStandaloneSetup _systemStandaloneSetup = new SystemStandaloneSetup();
    _systemStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
