/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.repository


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RepositoryStandaloneSetup extends RepositoryStandaloneSetupGenerated {

	def static void doSetup() {
		new RepositoryStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
