/*
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation.parser.antlr;

import com.google.inject.Inject;
import edu.kit.ipd.sdq.mdsdpc.allocation.parser.antlr.internal.InternalAllocationParser;
import edu.kit.ipd.sdq.mdsdpc.allocation.services.AllocationGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AllocationParser extends AbstractAntlrParser {

	@Inject
	private AllocationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAllocationParser createParser(XtextTokenStream stream) {
		return new InternalAllocationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Allocation";
	}

	public AllocationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AllocationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
