/**
 * generated by Xtext 2.9.1
 */
package edu.kit.ipd.sdq.mdsdpc.allocation.ui.contentassist;

import edu.kit.ipd.sdq.mdsdpc.allocation.ui.contentassist.AbstractAllocationProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class AllocationProposalProvider extends AbstractAllocationProposalProvider {
}
